### ISSUE TITLE
v0.40.0 Errors to build on TypeScript - No exported member 'GameMetadata'

### ISSUE THREAD

**Issue by evandroabukamel** [boardgameio/boardgame.io#809]
Hey, guys.
Recently I've installed the v0.40.0 to try it but I couldn't build my project in TypeScript.

```
node_modules/bgio-storage-cache/dist/bgio-storage-cache.d.ts:9:38 - error TS2694: Namespace '"./node_modules/boardgame.io/dist/types/src/types".Server' has no exported member 'GameMetadata'.

9         metadata: LRU<string, Server.GameMetadata>;
                                       ~~~~~~~~~~~~

node_modules/bgio-storage-cache/dist/bgio-storage-cache.d.ts:47:50 - error TS2694: Namespace '"./node_modules/boardgame.io/dist/types/src/types".Server' has no exported member 'GameMetadata'.

47     setMetadata(gameID: string, metadata: Server.GameMetadata): Promise<void>;
                                                    ~~~~~~~~~~~~
```

That's it. I didn't have time to investigate yet. I still have to work on my PR.

**Comment by delucis** [comment]
Hi @evandroabukamel, that’s expected. That type was renamed in 0.40.0: `Server.GameMetadata` → `Server.MatchData`.

There’s a full list of breaking changes in the #709 PR.

**Comment by delucis** [comment]
Oh, but I’m only now noticing the error is actually originating from `bgio-storage-cache` — it’s possible an update is needed there for compatibility with 0.40.0.

**Comment by delucis** [comment]
@evandroabukamel Just released bgio-storage-cache@0.2.0 which should fix this.
