### ISSUE TITLE
Bug to build on release 0.39.14

### ISSUE THREAD

**Issue by evandroabukamel** [boardgameio/boardgame.io#751]
Hello, everyone.

Recently I installed the version 0.39.14 but I got the following error when building my project.

```
node_modules/boardgame.io/dist/types/src/client/client.d.ts:3:19 - error TS2307: Cannot find module './debug' or its corresponding type declarations.
3 import Debug from './debug';

node_modules/boardgame.io/dist/types/src/client/react.d.ts:1:19 - error TS2307: Cannot find module 'react' or its corresponding type declarations.
1 import React from 'react';

node_modules/boardgame.io/dist/types/src/client/react.d.ts:41:19 - error TS2503: Cannot find namespace 'JSX'.
41         render(): JSX.Element;
```

**Comment by delucis** [comment]
Thanks for the report. Looks like a bug from converting the clients to Typescript (#744).

Need to do some more debugging but here's where I think the errors are coming from.

1. The debug implementation is all in JavaScript so after `tsc` compiles, there's no types for it in `dist`. Not sure why I don't see this error in my projects, but writing a `.d.ts` for the debug panel may help here.

2. & 3. The React props for the board are currently exported directly from the main types file, but they rely on type namespaces provided by React which won't be present for projects who aren't using React. I probably have to figure out a way to export these from a React-specific module.
